<?php


/** @var \Geexu\Blog\Block\Post\View $block */
$_post = $block->getPost();
?>
<!--Open Graph Meta tags -->
<meta property="og:url"             content="<?= /* @noEscape */ $_post->getUrl() ?>" />
<meta property="og:title"           content="<?= /* @noEscape */ $_post->getName() ?>" />
<meta property="og:image"           content="<?= /* @noEscape */ $block->getImageUrl($_post->getImage()) ?>" />
<meta property="og:description"    content="<?= /* @noEscape */ $_post->getShortDescription() ?>" />
<!--End Open Graph Meta tags-->
