<?php


/** @var \Geexu\Blog\Model\ResourceModel\Post\Collection $posts */
/** @var \Geexu\Blog\Block\Post\RelatedPost $block */
$posts = $block->getRelatedPostList();
if ($posts && $block->isEnabledBlog()): ?>
    <h2><?= $posts->getSize() ? __('Related Posts') : __('No Related Posts') ?></h2>
    <?php if ($block->getRelatedMode()):?>
        <div class="owl-carousel owl-theme">
            <?php foreach ($posts as $post): ?>
                <div class="item post-list-item col-mp post-item-list mp-4">
                    <div class="post-item-wraper">
                        <div class="post-info-wraper">
                            <a href="<?= $post->getUrl() ?>">
                                <img class="img-responsive"
                                     src="<?= $block->resizeImage($post->getImage(), '400x'); ?>"
                                     alt="<?= $block->escapeHtml($post->getName()); ?>"/>
                            </a>
                            <h2 class="mp-post-title" style="margin: 20px 0;">
                                <a class="post-link-title" title="<?= $block->escapeHtml($post->getName()); ?>"
                                   href="<?= $post->getUrl() ?>"><?= $post->getName(); ?></a>
                            </h2>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <script>
        require([
            'jquery',
            'owlCarousel'
            ], function ($) {
            'use strict';
            $(document).ready(function(){
                $(".owl-carousel").owlCarousel({
                    items:2,
                    loop:false,
                    margin:10,
                    responsive:{
                        600:{
                            items:4
                        }
                    }
                });
            });
        });
    </script>
    <?php else:?>
        <ul>
            <?php foreach ($posts as $post): ?>
                <li><a href="<?= $post->getUrl() ?>"><?= $post->getName(); ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif;?>
<?php endif; ?>
