<?php


$topics = $block->getTopicList();
if ($topics && $topics->getSize()):
    ?>
    <div class="mp-sidebar mpcss">
        <div class="row">
            <div class="block-title col-xs-12 sidebar-categories">
                <p class="block-mp-sidebar-heading" role="heading" aria-level="2"><?= __('Topics') ?></p>
            </div>
            <div class="col-xs-12">
                <ul class="block-content menu-categories">
                    <?php foreach ($topics as $topic): ?>
                        <li class="category-item">
                            <a class="list-categories" href="<?= $block->getTopicUrl($topic) ?>">
                                <i class="fa fa-folder-o" aria-hidden="true">&nbsp;</i>
                                <?= ucfirst($topic->getName()) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
