<?php

/** @var \Geexu\Blog\Helper\Data $helper */
$helper = $this->helper(\Geexu\Blog\Helper\Data::class);
?>

<?php if ($helper->isEnabled()): ?>
    <?php if ($helper->getBlogConfig('general/footer')): ?>
        <li>
            <a <?= $block->getLinkAttributes() ?>>
                <?= $block->escapeHtml($block->getLabel()); ?>
                <?= ($block->getCounter()) ? '<span>' . $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>
            </a>
        </li>
    <?php endif; ?>
    <?php if ($helper->getBlogConfig('general/display_sitemap')): ?>
        <li>
            <a href="<?= $block->getHtmlSiteMapUrl() ?>">
                <?= __('Sitemap'); ?>
                <?= ($block->getCounter()) ? '<span>' . $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>
            </a>
        </li>
    <?php endif; ?>
<?php endif; ?>
