<?php

$tree = $block->getTree();
if ($tree):
    ?>
    <div class="mp-sidebar mpcss">
        <div class="row">
            <div class="block-title col-xs-12 sidebar-categories">
                <p class="block-mp-sidebar-heading" role="heading" aria-label="2"><?= __('Categories') ?></p>
            </div>
            <div class="col-xs-12">
                <?= $block->getCategoryTreeHtml($tree) ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(['Geexu_Blog/js/categorytree'], function () {
        });
    </script>
<?php endif; ?>
